/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  corePlugins: {
    // Enable all core plugins
    preflight: true,
    container: true,
    space: true,
    divideWidth: true,
    divideColor: true,
    divideStyle: true,
    divideOpacity: true,
    accessibility: true,
    appearance: true,
    backgroundAttachment: true,
    backgroundClip: true,
    backgroundColor: true,
    backgroundImage: true,
    gradientColorStops: true,
    backgroundOpacity: true,
    backgroundPosition: true,
    backgroundRepeat: true,
    backgroundSize: true,
    borderCollapse: true,
    borderColor: true,
    borderOpacity: true,
    borderRadius: true,
    borderStyle: true,
    borderWidth: true,
    boxSizing: true,
    cursor: true,
    display: true,
    flexDirection: true,
    flexWrap: true,
    placeItems: true,
    placeContent: true,
    placeSelf: true,
    alignItems: true,
    alignContent: true,
    alignSelf: true,
    justifyItems: true,
    justifyContent: true,
    justifySelf: true,
    flex: true,
    flexGrow: true,
    flexShrink: true,
    order: true,
    float: true,
    clear: true,
    fontFamily: true,
    fontWeight: true,
    height: true,
    fontSize: true,
    lineHeight: true,
    listStylePosition: true,
    listStyleType: true,
    margin: true,
    maxHeight: true,
    maxWidth: true,
    minHeight: true,
    minWidth: true,
    objectFit: true,
    objectPosition: true,
    opacity: true,
    outline: true,
    overflow: true,
    overscrollBehavior: true,
    padding: true,
    placeholderColor: true,
    placeholderOpacity: true,
    pointerEvents: true,
    position: true,
    inset: true,
    resize: true,
    boxShadow: true,
    fill: true,
    stroke: true,
    strokeWidth: true,
    tableLayout: true,
    textAlign: true,
    textColor: true,
    textOpacity: true,
    textOverflow: true,
    textDecoration: true,
    textTransform: true,
    userSelect: true,
    verticalAlign: true,
    visibility: true,
    whitespace: true,
    width: true,
    wordBreak: true,
    zIndex: true,
    gap: true,
    gridAutoFlow: true,
    gridTemplateColumns: true,
    gridAutoColumns: true,
    gridColumn: true,
    gridColumnStart: true,
    gridColumnEnd: true,
    gridTemplateRows: true,
    gridAutoRows: true,
    gridRow: true,
    gridRowStart: true,
    gridRowEnd: true,
    transform: true,
    transformOrigin: true,
    scale: true,
    rotate: true,
    translate: true,
    skew: true,
    transitionProperty: true,
    transitionTimingFunction: true,
    transitionDuration: true,
    transitionDelay: true,
    animation: true,
  },
  theme: {
    extend: {
      colors: {
        black: "#000000",
        white: "#ffffff",
        green: {
          300: "#6ee7b7",
          400: "#34d399",
          500: "#10b981",
          600: "#059669",
        },
        gray: {
          300: "#d1d5db",
          400: "#9ca3af",
          500: "#6b7280",
          700: "#374151",
          800: "#1f2937",
          900: "#111827",
        },
      },
    },
  },
  plugins: [],
}; 